### ISSUE TITLE
not enough values to unpack (expected 13, got 7)

### ISSUE THREAD

**Issue by Eurus-Holmes** [soujanyaporia/multimodal-fusion#2]
when I run `python run.py --unimodal True --fusion True`

error:
```
Namespace(fusion=True, unimodal=True)
Training unimodals first
('starting unimodal ', 'text')
Traceback (most recent call last):
  File "run.py", line 415, in <module>
    unimodal(mode)
  File "run.py", line 240, in unimodal
    (train_data, train_label, _, _, test_data, test_label, _, train_length, _, test_length, _, _, _) = u.load()
ValueError: not enough values to unpack (expected 13, got 7)
```
how can I solve it...

**Comment by SenticNet** [comment]
It is fixed now

**Comment by Eurus-Holmes** [comment]
Hi @SenticNet  , thanks for your great work, but this error is still existed...

**Comment by soujanyaporia** [comment]
You should use unimodal-most.pickle

**Comment by soujanyaporia** [comment]
For other datasets, I will soon upload the pickle files.

**Comment by Eurus-Holmes** [comment]
Hi @soujanyaporia , thanks for your response, I have used unimodel-mosi.pickle, 
error again...
```
Training unimodals first
('starting unimodal ', 'text')
Traceback (most recent call last):
  File "run.py", line 430, in <module>
    unimodal(mode)
  File "run.py", line 254, in unimodal
    (train_data, train_label, _, _, test_data, test_label, _, train_length, _, test_length, _, _, _) = u.load()
ValueError: not enough values to unpack (expected 13, got 10)
```
how can I fix it...

**Comment by soujanyaporia** [comment]
I see, can you use --unimodal False in the argument? I have to upload the correct unimodal files which will take sometime. Have not maintained those since last year.

**Comment by soujanyaporia** [comment]
Can you try this?- (train_data, train_label, test_data, test_label, maxlen, train_length, test_length) = u.load()

**Comment by Eurus-Holmes** [comment]
Oh, I see, thank you very much.
Best Wishes.
